from typing import Iterable, Iterator, Protocol


class FlatFsReader(Protocol):
    """Read-only interface to access files in the flat filesystem."""

    def scan(self) -> Iterator[str]:
        """Scan filesystem and generate paths to existing files.

        Each yielded path can later be used with other methods of this
        interface.
        """
        ...

    def exists(self, path: str) -> bool:
        """Check if *path* points to an existing file."""
        ...

    def read_bytes(self, path: str) -> bytes:
        """Read entire file and return as bytes.

        If *path* does not point to an existing file,
        :exc:`flatfs.exc.PathNotFoundError` will be raised.

        :param path:
            The path to a file to read.
        """
        ...

    def read_chunks(self, path: str, chunk_size: int = 65535) -> Iterator[bytes]:
        """Read file in chunks and return iterator yielding chunks.

        This method can be safely used with large files without the risk of
        getting out of memory.

        If *path* does not point to an existing file,
        :exc:`flatfs.exc.PathNotFoundError` will be raised.

        :param path:
            The path to a file to read.

        :param chunk_size:
            The maximum chunk size (in bytes).

            This is the maximum length of a single generated bytes object.
        """
        ...


class FlatFsReaderWriter(FlatFsReader, Protocol):
    """Read-write interface to access files in the flat filesystem."""

    def write_bytes(self, path: str, data: bytes):
        """Create or overwrite file at given *path* using *data* as file content.

        :param path:
            The path to a file to create or modify.

        :param data:
            The data to write to a file.

            It will replace any existing file content, and will become the new
            file content.
        """
        ...

    def write_chunks(self, path: str, chunks: Iterable[bytes]):
        """Create or overwrite file at given *path* and write chunks of data
        generated by provided *chunks* iterable.

        :param path:
            The path to a file to create or modify.

        :param chunks:
            Iterable providing chunks of bytes to write to a file.
        """
        ...

    def remove(self, path: str):
        """Remove file at given *path*.

        Raises :exc:`flatfs.exc.PathNotFoundError` if there was no file to
        remove at given *path*.

        :param path:
            The path to a file to remove.
        """
        ...
