from typing import AsyncGenerator, AsyncIterable, Iterable, Iterator, Protocol

from . import _export

__all__ = export = _export.Export()  # type: ignore


@export
class SupportsReadChunks(Protocol):
    """Protocol for objects that support chunked reading."""

    def read_chunks(self, path: str, chunk_size: int = 65535) -> Iterator[bytes]:
        """Read file in chunks and return iterator yielding chunks.

        This method can be safely used with large files without the risk of
        getting out of memory.

        If *path* does not point to an existing file,
        :exc:`flatfs.exc.PathNotFoundError` will be raised.

        :param path:
            The path to a file to read.

        :param chunk_size:
            The maximum chunk size (in bytes).

            This is the maximum length of a single generated bytes object.
        """
        ...


@export
class SupportsWriteChunks(Protocol):
    """Protocol for object that support writing in chunks."""

    def write_chunks(self, path: str, chunks: Iterable[bytes]):
        """Create or overwrite file at given *path* and write chunks of data
        generated by provided *chunks* iterable.

        :param path:
            The path to a file to create or modify.

        :param chunks:
            Iterable providing chunks of bytes to write to a file.
        """
        ...


@export
class FlatFsReader(SupportsReadChunks, Protocol):
    """Read-only interface to access files in the flat filesystem."""

    def scan(self) -> Iterator[str]:
        """Scan filesystem and generate paths to existing files.

        Each yielded path can later be used with other methods of this
        interface.
        """
        ...

    def exists(self, path: str) -> bool:
        """Check if *path* points to an existing file."""
        ...


@export
class FlatFsReaderWriter(FlatFsReader, SupportsWriteChunks, Protocol):
    """Read-write interface to access files in the flat filesystem."""

    def remove(self, path: str):
        """Remove file at given *path*.

        Raises :exc:`flatfs.exc.PathNotFoundError` if there was no file to
        remove at given *path*.

        :param path:
            The path to a file to remove.
        """
        ...


@export
class SupportsAsyncReadChunks(Protocol):

    def read_chunks(self, path: str, chunk_size: int = 65535) -> AsyncGenerator[bytes, None]:
        """Read file in chunks and return iterator yielding chunks.

        This method can be safely used with large files without the risk of
        getting out of memory.

        If *path* does not point to an existing file,
        :exc:`flatfs.exc.PathNotFoundError` will be raised.

        :param path:
            The path to a file to read.

        :param chunk_size:
            The maximum chunk size (in bytes).

            This is the maximum length of a single generated bytes object.
        """
        ...


@export
class SupportsAsyncWriteChunks(Protocol):

    async def write_chunks(self, path: str, chunks: AsyncIterable[bytes]):
        """Create or overwrite file at given *path* and write chunks of data
        generated by provided *chunks* iterable.

        :param path:
            The path to a file to create or modify.

        :param chunks:
            Iterable providing chunks of bytes to write to a file.
        """
        ...


@export
class AsyncFlatFsReader(SupportsAsyncReadChunks, Protocol):
    """Async read-only interface to access files in the flat filesystem."""

    def scan(self) -> AsyncGenerator[str, None]:
        """Scan filesystem and generate paths to existing files.

        Each yielded path can later be used with other methods of this
        interface.
        """
        ...

    async def exists(self, path: str) -> bool:
        """Check if *path* points to an existing file."""
        ...


@export
class AsyncFlatFsReaderWriter(AsyncFlatFsReader, SupportsAsyncWriteChunks, Protocol):
    """Async read-write interface to access files in the flat filesystem."""

    async def remove(self, path: str):
        """Remove file at given *path*.

        Raises :exc:`flatfs.exc.PathNotFoundError` if there was no file to
        remove at given *path*.

        :param path:
            The path to a file to remove.
        """
        ...
