name: CI

on: [push, pull_request]

jobs:
  check-all:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/poetry-install
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check all
      run: |
        poetry run inv check-all

  bump:
    needs: check-all
    runs-on: ubuntu-slim
    if: github.ref == 'refs/heads/feat/github-actions' && success() # FIXME: replace with `main`
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: ./.github/actions/poetry-install
      with:
        python-version: 3.13
    - name: Perform version bump
      run: |
        poetry run inv bump
    - name: Push tags to repository
      run: |
        git push --tags
